  name: Build, Test and Deploy

  on:
    push:
      branches: [main]
    workflow_dispatch: 

  jobs:

    build:
      runs-on: ubuntu-22.04
      steps:
        - name: Cloner le repo
          run: git clone https://github.com/h-khribich/hamzaAction.git

        - name: Construire le front (npm)
          run: |
            cd hamzaAction/frontend
            npm install
            npm run build

    test:
      runs-on: ubuntu-22.04
      needs: build
      steps: 
        - name: Cloner le repo
          run: git clone https://github.com/h-khribich/hamzaAction.git

        - name: Lancer la base de données via Docker Compose
          run: |
            cd hamzaAction
            docker compose -f docker-local-bdd.yml up -d

        - name: Attendre MariaDB
          run: sleep 15

        - name: Lancer le backend + BDD via Docker Compose
          run: |
            cd hamzaAction
            docker compose -f docker-back-build.yml up -d

        - name: Lancer les tests e2e
          run: |
            cd hamzaAction/frontend
            npm install
            npm run build
            npx cypress run --config baseUrl=http://localhost:517

    deploy:
      runs-on: ubuntu-22.04
      needs: test
      steps:
        - name: Simulation de déploiement
          run: echo "Mock deploy - Votre application serait déployée ici" 