name: Snyk Security

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
      SNYK_ORG_ID:
        required: false

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache backend node_modules
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Snyk Code test (SAST) -> generate SARIF (won't fail the job)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: ./backend
        run: |
          # utilise npx pour exécuter la CLI Snyk installée temporairement si non présente
          npx snyk code test --sarif > ../snyk-code.sarif || true

      - name: Snyk Open Source (SCA) test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: ./backend
        run: |
          npx snyk test --severity-threshold=medium --org=${{ secrets.SNYK_ORG_ID }} || true

      - name: Snyk Open Source monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: ./backend
        run: |
          npx snyk monitor --all-projects || true

      - name: Snyk IaC test and report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npx snyk iac test --report || true

      # Optionnel: upload du SARIF vers GitHub Code Scanning (nécessite permission security-events: write)
      - name: Upload Snyk Code SARIF to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
