  name: E2E

  on: 
    workflow_call: {}

  jobs:
    test:
      runs-on: ubuntu-22.04
      steps: 
        - uses: actions/checkout@v4

        - name: Start BDD
          run: docker compose -f docker-local-bdd.yml up -d

        - name: Start Backend
          run: docker compose -f docker-back-build.yml up -d

        - name: Wait for API (tcp 12000)
          run: npx wait-on tcp:127.0.0.1:12000

        - name: Install deps front
          working-directory: frontend
          run: npm ci

        - name: Run Vite (bg) and wait
          working-directory: frontend
          run: |
            npm run dev -- --host --port 5173
            npx wait-on http://localhost:5173

        - name: Cypress
          working-directory: frontend
          env:
            CYPRESS_baseUrl: http://127.0.0.1:5173
          run: npx cypress run